- hosts: repository
  tasks:
    - name: update distro to latest
      yum: name=* state=latest

    - name: Install OpenJDK
      yum: name={{ item }} state=latest
      with_items:
      - java-1.8.0-openjdk-devel
      - open-vm-tools
      - libselinux-python

    - name: Remove unneeded stuff
      yum: name={{ item }} state=removed
      with_items:
          - wpa_supplicant
          - postfix

    - name: disable selinux
      selinux: state=disabled

    - name: add login keys
      authorized_key: user=root key="{{ item }}"
      with_file:
        - keys
    - name: Enable nexus to be started at boot
      service: name=nexus enabled=yes state=started


  roles:
  - role: jdauphant.nginx
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
    nginx_sites:
      repository:
        - listen 80 default_server
        - server_name repository repository.ci.wildfly.org _
        - location / { proxy_pass http://127.0.0.1:9999/;
                               proxy_http_version  1.1; }
    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP  $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  - role: ansible-nexus
    nexus_properties: { 'nexus-work': '/store/nexus',
                        'application-port': 9999,
                       'nexus-webapp-context-path': '/' }
