- hosts: repository
  roles:
  - role: nginx,
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
    nginx_sites:
      repository:
        - listen 80 default_server
        - server_name repository repository.ci.wildfly.org _
        - location / { proxy_pass http://127.0.0.1:9999/;
                               proxy_http_version  1.1; }
    nginx_configs:
      proxy:
        - proxy_set_header X-Real-IP  $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  - role: nexus,
    nexus_properties: {'application-port': 9999,
                       'nexus-webapp-context-path': '/' }
