---
# This playbook deploys a jdk9 on agents

- hosts: build60-win
  user: root
  vars:
    jdk8_file_name: jdk1.8.0_92-win32.zip
    teamcity_server_host: http://teamcity.brontes.local
  roles:
    - win-initial
