---

#- name: stop agent
#  service: name=teamcity-agent state=stopped

- name: remove old JDK10
  file: path={{ item }} state=absent
  with_items:
    - /usr/java/jdk-10

- name: Extract JDK10
  unarchive: src=/store/jdk/{{ jdk10_file_name }} dest=/usr/java creates=/usr/java/jdk-10

- name: Configure buildAgent.properties
  lineinfile:
    dest="/opt/buildAgent/conf/buildAgent.properties"
    line="env.JDK_10=/usr/java/jdk-10"
    regexp="env.JDK_10=.*"
    state=present


#- name: Restart agent to apply new JDKs
#  service: name=teamcity-agent enabled=yes state=restarted
