---
- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: Install docker CE
  yum: name={{ item }} state=present
  with_items:
   - docker-ce
   - python-pip

- name:
   pip:
    name: docker-compose

- user:
    name: teamcity
    groups: docker
    append: yes

- name: Enable docker
  service: name=docker enabled=yes state=restarted
