---

- name: stop agent
  win_service: name=TCBuildAgent state=stopped
- name: copy JDK 10
  win_copy: src=/store/jdk/jdk-10.0.1-win64.zip dest="C:\Java\jdk10.zip"

- name: copy JDK 11
  win_copy: src=/store/jdk/openjdk-11-ea+18_windows-x64_bin.zip dest="C:\Java\jdk11.zip"

- name: extract JDK 10
  win_unzip: src="C:\Java\jdk10.zip" dest="C:\Java" creates="C:\Java\jdk-10.0.1" rm=True
  
- name: extract JDK 11
  win_unzip: src="C:\Java\jdk11.zip" dest="C:\Java" creates="C:\Java\jdk-11" rm=True


- name: "agent jdk 10"
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_10=C:\\\\Java\\\\jdk-10.0.1"
    regexp="env.JDK_10=.*"
    state=present

- name: "agent jdk 11"
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_11=C:\\\\Java\\\\jdk-11"
    regexp="env.JDK_11=.*"
    state=present
        
- name: cleanup
  win_file: path={{ item }} state=absent
  with_items:
    - C:\Java\jdk10.zip
    - C:\Java\jdk11.zip

- name: Restart agent to apply new JDKs
  win_service: name=TCBuildAgent start_mode=auto state=restarted
