---
# This role adds rng

- name: Install haveged deamon
  yum: name={{ item }} state=present
  with_items:
   - haveged

- name: Enable haveged service to be started at boot
  service: name=haveged enabled=yes state=started
