---

- name: stop agent
  service: name=teamcity-agent state=stopped

- name: remove old JDK9
  file: path={{ item }} state=absent
  with_items:
    - /usr/java/jdk-9
    - /usr/java/jigsaw/jdk-9

- name: Extract JDK9 EA
  unarchive: src=/store/jdk/{{ jdk9_file_name }} dest=/usr/java creates=/usr/java/jdk-9

- name: Configure buildAgent.properties
  lineinfile:
    dest="/opt/buildAgent/conf/buildAgent.properties"
    line="env.JDK_19=/usr/java/jdk-9"
    regexp="env.JDK_19=.*"
    state=present

- name: Restart agent to apply new JDKs
  service: name=teamcity-agent enabled=yes state=restarted
