---

- name: stop agent
  win_service: name=TCBuildAgent state=stopped

- name: clean maven repo & teamcity work dirs
  win_file: path={{ item }} state=absent
  with_items:
    - c:\store\repository
    - C:\BuildAgent\logs
    - C:\BuildAgent\temp

- name: clean work
  raw: rm -Force -Recurse C:\BuildAgent\work

- name: Restart agent
  win_service: name=TCBuildAgent start_mode=auto state=restarted