---
- name: install packages
  win_chocolatey:
  name: {{ item }}
  with_items:
      - git
      - putty
  state: present

win_chocolatey:
  name: powershell
  state: present
  upgrade: true

- name: copy JDKs
  win_copy: src=/store/jdk/jdk1.7.0_80-windows-i586.zip dest="C:\Java\jdk7.zip"
  win_copy: src=/store/jdk/jdk1.8.0_131-windows-i586.zip dest="C:\Java\jdk8.zip"

- name: extract JDK
  win_unzip: src="C:\Java\jdk-8.zip" dest="C:\Java" creates="C:\Java\jdk1.8.0_131" rm=True
  win_unzip: src="C:\Java\jdk-7.zip" dest="C:\Java" creates="C:\Java\jdk1.7.0_80" rm=True

- name: setup env vars
  win_environment:
    state: present
    name: JAVA_HOME
    value: C:\Java\jdk1.8.0_131
    level: machine

- name: Download earthrise.jpg to specified path
  win_get_url:
    url: http://brontes.brontes.local/update/buildAgent.zip
    dest: C:\store\buildAgent.zip

- name: extract build agent
  win_unzip:
    src: C:\store\buildAgent.zip
    dest: C:\
    creates: C:\buildAgent 
    rm: True

- name: install service
  win_shell: C:\buildAgent\bin\service.install.bat

  
#- name: stop agent
#  win_service: name=TCBuildAgent state=stopped

#- name: Copy Open JDK 8
#  win_copy: src=/store/jdk/{{ openjdk8_file_name }} dest="C:\opt\java\openjdk-8.zip"

#- name: Copy Oracle JDK 8
#  win_copy: src=/store/jdk/{{ jdk8_file_name }} dest="C:\opt\java\jdk-8.zip"

#- name: Extract OpenJDK8
#  win_unzip: src="C:\opt\java\openjdk-8.zip" dest="C:\opt\java" creates="C:\opt\java\java-1.8.0-openjdk-1.8.0.71-0.b15.windows.x86_64" rm=True

#- name: Extract Oracle JDK8
#  win_unzip: src="C:\opt\java\jdk-8.zip" dest="C:\opt\java" creates="C:\opt\java\jdk1.8.0_92" rm=True

- name: Configure buildAgent.properties
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_18=C:\\\\opt\\\\java\\\\jdk1.8.0_131"
    regexp="env.JDK_18=.*"
    state=present
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_17=C:\\\\opt\\\\java\\\\jdk1.7.0_80"
    regexp="env.JDK_17=.*"
    state=present

- name: Restart agent to apply new JDKs
  win_service: name=TCBuildAgent start_mode=auto state=restarted
