---
- name: install packages
  win_chocolatey:
   name: git
   state: present

#win_chocolatey:
#  name: powershell
#  state: present
#  upgrade: true

- name: copy JDK 7
  win_copy: src=/store/jdk/jdk1.7.0_80-windows-i586.zip dest="C:\Java\jdk7.zip"

- name: copy JDK 8
  win_copy: src=/store/jdk/jdk1.8.0_131-windows-i586.zip dest="C:\Java\jdk8.zip"

- name: extract JDK 8
  win_unzip:
       src: C:\Java\jdk8.zip
       dest: C:\Java
       creates: C:\Java\jdk1.8.0_131
       rm: True

- name: extract JDK 7
  win_unzip: src="C:\Java\jdk7.zip" dest="C:\Java" creates="C:\Java\jdk1.7.0_80" rm=True

- name: setup env vars
  win_environment:
    state: present
    name: JAVA_HOME
    value: C:\Java\jdk1.8.0_131
    level: machine

- name: add java to path
  win_path:
    name: PATH
    elements: "%JAVA_HOME%\bin"
    state: present

- name: Download agent
  win_get_url:
    url: {{ teamcity_server_host }}/update/buildAgent.zip
    dest: C:\store\buildAgent.zip

- name: extract build agent
  win_unzip:
    src: C:\store\buildAgent.zip
    dest: C:\buildAgent
    creates: C:\buildAgent
    rm: True

- name: Configure buildAgent.properties
  win_lineinfile:
    dest="C:\\BuildAgent\\launcher\\conf\\wrapper.conf"
    line="wrapper.java.command=C:\\\\opt\\\\java\\\\jdk1.8.0_131\\\\bin\\\\java.exe"
    regexp="wrapper.java.command=.*"
    state=present

- name: install agent
  win_command: C:\buildAgent\bin\install.bat {{ teamcity_server_host }}

  
#- name: stop agent
#  win_service: name=TCBuildAgent state=stopped

#- name: Copy Open JDK 8
#  win_copy: src=/store/jdk/{{ openjdk8_file_name }} dest="C:\opt\java\openjdk-8.zip"

#- name: Copy Oracle JDK 8
#  win_copy: src=/store/jdk/{{ jdk8_file_name }} dest="C:\opt\java\jdk-8.zip"

#- name: Extract OpenJDK8
#  win_unzip: src="C:\opt\java\openjdk-8.zip" dest="C:\opt\java" creates="C:\opt\java\java-1.8.0-openjdk-1.8.0.71-0.b15.windows.x86_64" rm=True

#- name: Extract Oracle JDK8
#  win_unzip: src="C:\opt\java\jdk-8.zip" dest="C:\opt\java" creates="C:\opt\java\jdk1.8.0_92" rm=True

- name: Configure buildAgent.properties
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_18=C:\\\\opt\\\\java\\\\jdk1.8.0_131"
    regexp="env.JDK_18=.*"
    state=present
- name: "agent"
  win_lineinfile:
    dest="C:\\BuildAgent\\conf\\buildAgent.properties"
    line="env.JDK_17=C:\\\\opt\\\\java\\\\jdk1.7.0_80"
    regexp="env.JDK_17=.*"
    state=present

- name: Restart agent to apply new JDKs
  win_service: name=TCBuildAgent start_mode=auto state=restarted
