---

- name: stop agent
  service: name=teamcity-agent state=stopped

- name: remove old jdks
  file: path={{ item }} state=absent
  with_items:
    - /opt/ibm/java-i386-80
    - /opt/ibm/java-i386-71

- shell: rm -rf /opt/*.tar.gz
- shell: rm -rf /usr/java/jdk*

- name: Download JDK7
  get_url: url={{ teamcity_server_url }}/agents-data/jdk-7u76-linux-i586.tar.gz dest=/opt/jdk-7u76-linux-i586.tar.gz

- name: Download IBM JDK7
  get_url: url={{ teamcity_server_url }}/agents-data/java-i386-71.tar.gz dest=/opt/java-i386-71.tar.gz

- name: Download IBM JDK8
  get_url: url={{ teamcity_server_url }}/agents-data/java-i386-80.tar.gz dest=/opt/java-i386-80.tar.gz

- name: Download Oracle JDK6
  get_url: url={{ teamcity_server_url }}/agents-data/jdk-6u45-linux-i586.tar.gz dest=/opt/jdk-6u45-linux-i586.tar.gz

- name: Download Oracle JDK8
  get_url: url={{ teamcity_server_url }}/agents-data/jdk-8u112-linux-i586.tar.gz dest=/opt/jdk-8u112-linux-i586.tar.gz

- name: Download Oracle JDK9 EA
  get_url: url={{ teamcity_server_url }}/agents-data/jdk-9-ea+143_linux-x86_bin.tar.gz  dest=/opt/jdk-9-ea+143_linux-x86_bin.tar.gz

- name: Extract JDK6
  unarchive: src=/opt/jdk-6u45-linux-i586.tar.gz dest=/usr/java copy=no

- name: Extract JDK7
  unarchive: src=/opt/jdk-7u76-linux-i586.tar.gz dest=/usr/java copy=no

- name: Extract JDK8
  unarchive: src=/opt/jdk-8u112-linux-i586.tar.gz dest=/usr/java copy=no

- name: Extract JDK9 EA
  unarchive: src=/opt/jdk-9-ea+143_linux-x86_bin.tar.gz dest=/usr/java copy=no

- name: Extract IBM JDK7
  unarchive: src=/opt/java-i386-71.tar.gz dest=/opt/ibm/ copy=no

- name: Extract IBM JDK8
  unarchive: src=/opt/java-i386-80.tar.gz dest=/opt/ibm/ copy=no

- name: Link default & latest jvm
  file: dest=/usr/java/latest src=/usr/java/jdk1.8.0_112 state=link owner=teamcity group=teamcity

- name: remove temp
  shell: rm -rf /opt/*.tar.gz

- name: Restart agent to apply new JDKs
  service: name=teamcity-agent enabled=yes state=restarted
