---
# deploy additional JDKs

- name: Download JDK7
  get_url: url={{ teamcity_server_url }}/agents-data/jdk-7u76-linux-i586.tar.gz dest=/opt/jdk-7u76-linux-i586.tar.gz

- name: Download IBM JDK7
  get_url: url={{ teamcity_server_url }}/agents-data/java-i386-71.tar.gz dest=/opt/java-i386-71.tar.gz

- name: Download IBM JDK8
  get_url: url={{ teamcity_server_url }}/agents-data/java-i386-80.tar.gz dest=/opt/java-i386-80.tar.gz

- name: Extract JDK7
  unarchive: src=/opt/jdk-7u76-linux-i586.tar.gz dest=/usr/java copy=no

- name: Extract IBM JDK7
  unarchive: src=/opt/java-i386-71.tar.gz dest=/opt copy=no

- name: Extract IBM JDK8
  unarchive: src=/opt/java-i386-80.tar.gz dest=/opt copy=no

#- name: Restart agent to apply new JDKs
#  service: name=teamcity-agent enabled=yes state=restarted

